# Generated by Django 3.0.4 on 2020-04-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
